package fp.repositorio;

public enum Language {
	JAVASCRIPT, CPLUSPLUS, JAVA, SHELL, HTML, C, CSS, COFFEESCRIPT, GO, RUBY, PYTHON, PHP, TYPESCRIPT, OBJECTIVEC,
	ASSEMBLY, SWIFT, RUST, VIMSCRIPT, CLOJURE, LUA, RASCAL, SCALA, MATLAB, VUE, PERL,KOTLIN,NOPROLAN,POWERSHELL,PUREBASIC

}
